# Generated by Django 2.1.4 on 2018-12-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='incomecategory',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='categoryName',
        ),
    ]
